
title: My Resume
url: 'http://inteltao.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Zui Tao
tagline: Graduate Stuednt at CMU
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: inteltao7@gmail.com
phone: 412 737 3022
website: inteltao.github.io #do not add http://
linkedin: zui-tao
github: inteltao
twitter: '@inteltao7'

#Update all the sections by editing the files inside _includes folder.
